---
title: "Aides Tests"
author: "Dr K"
date: "May 24, 2017"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
require(tigerstats)
require(dplyr)
Scarolina<-read.csv(file="south_carolina_aides.csv",header=TRUE)
korea<-read.csv(file="korea_aides.csv",header=TRUE)
cenAfrica<-read.csv(file="central_africa_aides.csv",header=TRUE)
```



Three new preventative aides drugs were tested in clinical trials in 2015. The trial designs were modeled after the famous RV_144 Aides Trials in Thailand in 2009.  Analyze and report on the apparent effectiveness of the three different drugs. Does sex of the participant seem to be a factor for any of the drugs?

#**Methods**
The data for the Aides Tests is large, having over 4000 observations, 3 variables, and includes the data from the clinical trials in 2015. To make the data easier to use, we must trim it down. We will be using r code stored in a separate .r file to help do this. We start with the Aides Tests data from 2015 and then use the select function from the dplyr package to extract 3 variables that we must study in regards to our research question, we will only be using the data from South Carolina, Central Africa, and Korea. We still need to clean the data up a bit more. This was done in the following way:
* We will subset each variable by sex to see if the drug is sex specific

# South Carolina

We will subset the data by sex to see if the drug is sex specific.  


# Central Africa

We will subset the data by sex to see if the drug is sex specific.


# Korea

We will subset the data by sex to see if the drug is sex specific.







